server:
  port: 8000
eureka:
  client:
    register-with-eureka: true #??? ??? ??
    fetch-registry: true
    service-url:
      defaultZone: http://localhost:8761/eureka

# global filter -> custom filter -> logging filter

spring:
  application:
    name: apigateway
  rabbitmq:
    host: 127.0.0.1
    port: 5672
    username: username
    password: password
  cloud:
    gateway: #  Netty ??? ?? ???? ??
      default-filters:
        - name: GlobalFilter
          args:
            baseMsg: Spring Cloud Gateway GlobalFilter
            preLogger: true
            postLogger: true
      routes:
        - id: first-service
          uri: lb://FIRST-SERVICE # ??? ??? ??? ???? ??
          predicates:
            - Path=/first-service/**
          filters:
              - RemoveRequestHeader=Cookie
              - RewritePath=/first-service/(?<segment>.*), /$\{segment}
#            - AddRequestHeader=first-request, first-requests-header2
#            - AddResponseHeader=first-response, first-response-header2
              - name: CustomFilter
              - name: LoggingFilter
                args:
                  baseMsg: Hi
                  preLogger: true
                  postLogger: true

management:
  endpoints:
    web:
      exposure:
        include: refresh, health, beans, httptrace, info, busrefresh  #refresh ? ??? cloud config env ? ??